const daftarSurah = {
  "1": { nama: "Al-Fatihah", arab: "الْفَاتِحَة", arti: "Pembukaan", type: "Makkiyah", ayat: 7 },
  "2": { nama: "Al-Baqarah", arab: "الْبَقَرَة", arti: "Sapi Betina", type: "Madaniyah", ayat: 286 },
  "3": { nama: "Ali Imran", arab: "آلُ عِمْرَان", arti: "Keluarga Imran", type: "Madaniyah", ayat: 200 },
  "4": { nama: "An-Nisa'", arab: "النِّسَاء", arti: "Wanita", type: "Madaniyah", ayat: 176 },
  "5": { nama: "Al-Ma'idah", arab: "الْمَائِدَة", arti: "Hidangan", type: "Madaniyah", ayat: 120 },
  "6": { nama: "Al-An'am", arab: "الْأَنْعَام", arti: "Binatang Ternak", type: "Makkiyah", ayat: 165 },
  "7": { nama: "Al-A'raf", arab: "الْأَعْرَاف", arti: "Tempat yang Tinggi", type: "Makkiyah", ayat: 206 },
  "8": { nama: "Al-Anfal", arab: "الْأَنْفَال", arti: "Harta Rampasan Perang", type: "Madaniyah", ayat: 75 },
  "9": { nama: "At-Taubah", arab: "التَّوْبَة", arti: "Pengampunan", type: "Madaniyah", ayat: 129 },
  "10": { nama: "Yunus", arab: "يُونُس", arti: "Nabi Yunus", type: "Makkiyah", ayat: 109 },
  "11": { nama: "Hud", arab: "هُود", arti: "Nabi Hud", type: "Makkiyah", ayat: 123 },
  "12": { nama: "Yusuf", arab: "يُوسُف", arti: "Nabi Yusuf", type: "Makkiyah", ayat: 111 },
  "13": { nama: "Ar-Ra'd", arab: "الرَّعْد", arti: "Guntur", type: "Madaniyah", ayat: 43 },
  "14": { nama: "Ibrahim", arab: "إِبْرَاهِيم", arti: "Nabi Ibrahim", type: "Makkiyah", ayat: 52 },
  "15": { nama: "Al-Hijr", arab: "الْحِجْر", arti: "Hijr", type: "Makkiyah", ayat: 99 },
  "16": { nama: "An-Nahl", arab: "النَّحْل", arti: "Lebah", type: "Makkiyah", ayat: 128 },
  "17": { nama: "Al-Isra'", arab: "الإِسْرَاء", arti: "Perjalanan Malam", type: "Makkiyah", ayat: 111 },
  "18": { nama: "Al-Kahf", arab: "الْكَهْف", arti: "Gua", type: "Makkiyah", ayat: 110 },
  "19": { nama: "Maryam", arab: "مَرْيَم", arti: "Maryam", type: "Makkiyah", ayat: 98 },
  "20": { nama: "Taha", arab: "طه", arti: "Taha", type: "Makkiyah", ayat: 135 },
  "21": { nama: "Al-Anbiya'", arab: "الْأَنْبِيَاء", arti: "Para Nabi", type: "Makkiyah", ayat: 112 },
  "22": { nama: "Al-Hajj", arab: "الْحَج", arti: "Haji", type: "Madaniyah", ayat: 78 },
  "23": { nama: "Al-Mu'minun", arab: "الْمُؤْمِنُونَ", arti: "Orang-orang yang Beriman", type: "Makkiyah", ayat: 118 },
  "24": { nama: "An-Nur", arab: "النُّور", arti: "Cahaya", type: "Madaniyah", ayat: 64 },
  "25": { nama: "Al-Furqan", arab: "الْفُرْقَان", arti: "Pembeda", type: "Makkiyah", ayat: 77 },
  "26": { nama: "Asy-Syu'ara'", arab: "الشُّعَرَاء", arti: "Penyair", type: "Makkiyah", ayat: 227 },
  "27": { nama: "An-Naml", arab: "النَّمْل", arti: "Semut", type: "Makkiyah", ayat: 93 },
  "28": { nama: "Al-Qasas", arab: "الْقَصَص", arti: "Kisah", type: "Makkiyah", ayat: 88 },
  "29": { nama: "Al-'Ankabut", arab: "الْعَنْكَبُوت", arti: "Laba-laba", type: "Makkiyah", ayat: 69 },
  "30": { nama: "Ar-Rum", arab: "الرُّوم", arti: "Bangsa Romawi", type: "Makkiyah", ayat: 60 },
  "31": { nama: "Luqman", arab: "لُقْمَان", arti: "Nabi Luqman", type: "Makkiyah", ayat: 34 },
  "32": { nama: "As-Sajdah", arab: "السَّجْدَة", arti: "Sujud", type: "Makkiyah", ayat: 30 },
  "33": { nama: "Al-Ahzab", arab: "الْأَحْزَاب", arti: "Kabilah-kabilah", type: "Madaniyah", ayat: 73 },
  "34": { nama: "Saba'", arab: "سَبَأ", arti: "Saba'", type: "Makkiyah", ayat: 54 },
  "35": { nama: "Fatir", arab: "فَاطِر", arti: "Pencipta", type: "Makkiyah", ayat: 45 },
  "36": { nama: "Ya-Sin", arab: "يس", arti: "Ya-Sin", type: "Makkiyah", ayat: 83 },
  "37": { nama: "As-Saffat", arab: "الصَّافَّات", arti: "Barisan", type: "Makkiyah", ayat: 182 },
  "38": { nama: "Sad", arab: "ص", arti: "Sad", type: "Makkiyah", ayat: 88 },
  "39": { nama: "Az-Zumar", arab: "الزُّمَر", arti: "Rombongan", type: "Makkiyah", ayat: 75 },
  "40": { nama: "Ghafir", arab: "غَافِر", arti: "Pengampun", type: "Makkiyah", ayat: 85 },
  "41": { nama: "Fussilat", arab: "فُصِّلَت", arti: "Penjelasan", type: "Makkiyah", ayat: 54 },
  "42": { nama: "Asy-Syura", arab: "الشُّورَى", arti: "Musyawarah", type: "Makkiyah", ayat: 53 },
  "43": { nama: "Az-Zukhruf", arab: "الزُّخْرُف", arti: "Perhiasan", type: "Makkiyah", ayat: 89 },
  "44": { nama: "Ad-Dukhan", arab: "الدُّخَان", arti: "Kabut", type: "Makkiyah", ayat: 59 },
  "45": { nama: "Al-Jasiyah", arab: "الْجَاثِيَة", arti: "Berlutut", type: "Makkiyah", ayat: 37 },
  "46": { nama: "Al-Ahqaf", arab: "الْأَحْقَاف", arti: "Bukit-bukit Pasir", type: "Makkiyah", ayat: 35 },
  "47": { nama: "Muhammad", arab: "مُحَمَّد", arti: "Nabi Muhammad", type: "Madaniyah", ayat: 38 },
  "48": { nama: "Al-Fath", arab: "الْفَتْح", arti: "Kemenangan", type: "Madaniyah", ayat: 29 },
  "49": { nama: "Al-Hujurat", arab: "الْحُجُرَات", arti: "Kamar-kamar", type: "Madaniyah", ayat: 18 },
   "50": { nama: "Qaf", arab: "ق", arti: "Qaf", type: "Makkiyah", ayat: 45 },
"51": { nama: "Adz-Dzariyat", arab: "الذَّارِيَات", arti: "Angin yang Menerbangkan", type: "Makkiyah", ayat: 60 },
"52": { nama: "At-Tur", arab: "الطُّور", arti: "Bukit", type: "Makkiyah", ayat: 49 },
"53": { nama: "An-Najm", arab: "النَّجْم", arti: "Bintang", type: "Makkiyah", ayat: 62 },
"54": { nama: "Al-Qamar", arab: "الْقَمَر", arti: "Bulan", type: "Makkiyah", ayat: 55 },
"55": { nama: "Ar-Rahman", arab: "الرَّحْمَن", arti: "Maha Pengasih", type: "Madaniyah", ayat: 78 },
"56": { nama: "Al-Waqi'ah", arab: "الْوَاقِعَة", arti: "Hari Kiamat", type: "Makkiyah", ayat: 96 },
"57": { nama: "Al-Hadid", arab: "الْحَدِيد", arti: "Besi", type: "Madaniyah", ayat: 29 },
"58": { nama: "Al-Mujadilah", arab: "الْمُجَادِلَة", arti: "Wanita yang Mengajukan Gugatan", type: "Madaniyah", ayat: 22 },
"59": { nama: "Al-Hasyr", arab: "الْحَشْر", arti: "Pengusiran", type: "Madaniyah", ayat: 24 },
"60": { nama: "Al-Mumtahanah", arab: "الْمُمْتَحَنَة", arti: "Wanita yang Diuji", type: "Madaniyah", ayat: 13 },
"61": { nama: "As-Saff", arab: "الصَّف", arti: "Barisan", type: "Madaniyah", ayat: 14 },
"62": { nama: "Al-Jumu'ah", arab: "الْجُمُعَة", arti: "Hari Jum'at", type: "Madaniyah", ayat: 11 },
"63": { nama: "Al-Munafiqun", arab: "الْمُنَافِقُونَ", arti: "Orang-orang Munafik", type: "Madaniyah", ayat: 11 },
"64": { nama: "At-Taghabun", arab: "التَّغَابُن", arti: "Hari Ditampakkan Segala Rahasia", type: "Madaniyah", ayat: 18 },
"65": { nama: "At-Talaq", arab: "الطَّلَاق", arti: "Talak", type: "Madaniyah", ayat: 12 },
"66": { nama: "At-Tahrim", arab: "التَّحْرِيم", arti: "Mengharamkan", type: "Madaniyah", ayat: 12 },
"67": { nama: "Al-Mulk", arab: "الْمُلْك", arti: "Kerajaan", type: "Makkiyah", ayat: 30 },
"68": { nama: "Al-Qalam", arab: "الْقَلَم", arti: "Pena", type: "Makkiyah", ayat: 52 },
"69": { nama: "Al-Haqqah", arab: "الْحَاقَّة", arti: "Hari Kiamat", type: "Makkiyah", ayat: 52 },
"70": { nama: "Al-Ma'arij", arab: "الْمَعَارِج", arti: "Tempat-tempat Naik", type: "Makkiyah", ayat: 44 },
"71": { nama: "Nuh", arab: "نُوح", arti: "Nabi Nuh", type: "Makkiyah", ayat: 28 },
"72": { nama: "Al-Jinn", arab: "الْجِن", arti: "Jin", type: "Makkiyah", ayat: 28 },
"73": { nama: "Al-Muzzammil", arab: "الْمُزَّمِل", arti: "Orang yang Berselimut", type: "Makkiyah", ayat: 20 },
"74": { nama: "Al-Muddatstsir", arab: "الْمُدَّثِّر", arti: "Orang yang Berkabung", type: "Makkiyah", ayat: 56 },
"75": { nama: "Al-Qiyamah", arab: "الْقِيَامَة", arti: "Hari Kiamat", type: "Makkiyah", ayat: 40 },
"76": { nama: "Al-Insan", arab: "الْإِنْسَان", arti: "Manusia", type: "Madaniyah", ayat: 31 },
"77": { nama: "Al-Mursalat", arab: "الْمُرْسَلَات", arti: "Angin yang Dikirim", type: "Makkiyah", ayat: 50 },
"78": { nama: "An-Naba'", arab: "النَّبَأ", arti: "Berita Besar", type: "Makkiyah", ayat: 40 },
"79": { nama: "An-Nazi'at", arab: "النَّازِعَات", arti: "Malaikat yang Mencabut", type: "Makkiyah", ayat: 46 },
"80": { nama: "'Abasa", arab: "عَبَس", arti: "Ia Bermuka Masam", type: "Makkiyah", ayat: 42 },
"81": { nama: "At-Takwir", arab: "التَّكْوِير", arti: "Menggulung", type: "Makkiyah", ayat: 29 },
"82": { nama: "Al-Infitar", arab: "الِانْفِطَار", arti: "Terbelah", type: "Makkiyah", ayat: 19 },
"83": { nama: "Al-Mutaffifin", arab: "الْمُطَفِّفِين", arti: "Orang-orang yang Curang", type: "Makkiyah", ayat: 36 },
"84": { nama: "Al-Insyiqaq", arab: "الِانْشِقَاق", arti: "Terbelah", type: "Makkiyah", ayat: 25 },
"85": { nama: "Al-Buruj", arab: "الْبُرُوج", arti: "Gugusan Bintang", type: "Makkiyah", ayat: 22 },
"86": { nama: "At-Tariq", arab: "الطَّارِق", arti: "Bintang yang Tampak di Malam Hari", type: "Makkiyah", ayat: 17 },
"87": { nama: "Al-A'la", arab: "الْأَعْلَى", arti: "Maha Tinggi", type: "Makkiyah", ayat: 19 },
"88": { nama: "Al-Ghashiyah", arab: "الْغَاشِيَة", arti: "Hari Pembalasan", type: "Makkiyah", ayat: 26 },
"89": { nama: "Al-Fajr", arab: "الْفَجْر", arti: "Fajar", type: "Makkiyah", ayat: 30 },
"90": { nama: "Al-Balad", arab: "الْبَلَد", arti: "Negeri", type: "Makkiyah", ayat: 20 },
  "91": { nama: "Asy-Syams", arab: "الشَّمْس", arti: "Matahari", type: "Makkiyah", ayat: 15 },
"92": { nama: "Al-Lail", arab: "اللَّيْل", arti: "Malam", type: "Makkiyah", ayat: 21 },
"93": { nama: "Adh-Dhuha", arab: "الضُّحَى", arti: "Waktu Dhuha", type: "Makkiyah", ayat: 11 },
"94": { nama: "Alam Nashrah", arab: "الْإِنْشِرَاح", arti: "Pembukaan", type: "Makkiyah", ayat: 8 },
"95": { nama: "At-Tin", arab: "التِّين", arti: "Buah Tin", type: "Makkiyah", ayat: 8 },
"96": { nama: "Al-'Alaq", arab: "الْعَلَق", arti: "Segumpal Darah", type: "Makkiyah", ayat: 19 },
"97": { nama: "Al-Qadr", arab: "الْقَدْر", arti: "Kemuliaan", type: "Makkiyah", ayat: 5 },
"98": { nama: "Al-Bayyinah", arab: "الْبَيِّنَة", arti: "Bukti yang Jelas", type: "Madaniyah", ayat: 8 },
"99": { nama: "Az-Zalzalah", arab: "الزَّلْزَلَة", arti: "Kegoncangan", type: "Madaniyah", ayat: 8 },
"100": { nama: "Al-'Adiyat", arab: "الْعَادِيَات", arti: "Kuda yang Berlari Kencang", type: "Makkiyah", ayat: 11 },
"101": { nama: "Al-Qari'ah", arab: "الْقَارِعَة", arti: "Hari Kiamat", type: "Makkiyah", ayat: 11 },
"102": { nama: "At-Takatsur", arab: "التَّكَاثُر", arti: "Bermegah-megahan", type: "Makkiyah", ayat: 8 },
"103": { nama: "Al-'Asr", arab: "الْعَصْر", arti: "Masa", type: "Makkiyah", ayat: 3 },
"104": { nama: "Al-Humazah", arab: "الْهُمَزَة", arti: "Pengumpat", type: "Makkiyah", ayat: 9 },
"105": { nama: "Al-Fil", arab: "الْفِيل", arti: "Gajah", type: "Makkiyah", ayat: 5 },
"106": { nama: "Quraisy", arab: "قُرَيْش", arti: "Suku Quraisy", type: "Makkiyah", ayat: 4 },
"107": { nama: "Al-Ma'un", arab: "الْمَاعُون", arti: "Barang yang Berguna", type: "Makkiyah", ayat: 7 },
"108": { nama: "Al-Kautsar", arab: "الْكَوْثَر", arti: "Nikmat yang Berlimpah", type: "Makkiyah", ayat: 3 },
"109": { nama: "Al-Kafirun", arab: "الْكَافِرُونَ", arti: "Orang-orang Kafir", type: "Makkiyah", ayat: 6 },
"110": { nama: "An-Nashr", arab: "النَّصْر", arti: "Pertolongan", type: "Madaniyah", ayat: 3 },
"111": { nama: "Al-Lahab", arab: "الْمَسَد", arti: "Gejolak Api", type: "Makkiyah", ayat: 5 },
"112": { nama: "Al-Ikhlas", arab: "الْإِخْلَاص", arti: "Ikhlas", type: "Makkiyah", ayat: 4 },
"113": { nama: "Al-Falaq", arab: "الْفَلَق", arti: "Waktu Subuh", type: "Makkiyah", ayat: 5 },
"114": { nama: "An-Nas", arab: "النَّاس", arti: "Manusia", type: "Makkiyah", ayat: 6 }
};
  