const daftarSurah = {
    1: { nama: "Al-Fatihah", arti: "Pembukaan", type: "Makkiyah", ayat: 7 },
    2: { nama: "Al-Baqarah", arti: "Sapi Betina", type: "Madaniyah", ayat: 286 },
    3: { nama: "Ali Imran", arti: "Keluarga Imran", type: "Madaniyah", ayat: 200 },
    4: { nama: "An-Nisa'", arti: "Wanita", type: "Madaniyah", ayat: 176 },
    5: { nama: "Al-Ma'idah", arti: "Hidangan", type: "Madaniyah", ayat: 120 },
    6: { nama: "Al-An'am", arti: "Binatang Ternak", type: "Makkiyah", ayat: 165 },
    7: { nama: "Al-A'raf", arti: "Tempat yang Tinggi", type: "Makkiyah", ayat: 206 },
    8: { nama: "Al-Anfal", arti: "Harta Rampasan Perang", type: "Madaniyah", ayat: 75 },
    9: { nama: "At-Taubah", arti: "Pengampunan", type: "Madaniyah", ayat: 129 },
    10: { nama: "Yunus", arti: "Nabi Yunus", type: "Makkiyah", ayat: 109 },
    11: { nama: "Hud", arti: "Nabi Hud", type: "Makkiyah", ayat: 123 },
    12: { nama: "Yusuf", arti: "Nabi Yusuf", type: "Makkiyah", ayat: 111 },
    13: { nama: "Ar-Ra'd", arti: "Guntur", type: "Madaniyah", ayat: 43 },
    14: { nama: "Ibrahim", arti: "Nabi Ibrahim", type: "Makkiyah", ayat: 52 },
    15: { nama: "Al-Hijr", arti: "Hijr", type: "Makkiyah", ayat: 99 },
    16: { nama: "An-Nahl", arti: "Lebah", type: "Makkiyah", ayat: 128 },
    17: { nama: "Al-Isra'", arti: "Perjalanan Malam", type: "Makkiyah", ayat: 111 },
    18: { nama: "Al-Kahf", arti: "Gua", type: "Makkiyah", ayat: 110 },
    19: { nama: "Maryam", arti: "Maryam", type: "Makkiyah", ayat: 98 },
    20: { nama: "Taha", arti: "Taha", type: "Makkiyah", ayat: 135 },
    21: { nama: "Al-Anbiya'", arti: "Para Nabi", type: "Makkiyah", ayat: 112 },
    22: { nama: "Al-Hajj", arti: "Haji", type: "Madaniyah", ayat: 78 },
    23: { nama: "Al-Mu'minun", arti: "Orang-orang yang Beriman", type: "Makkiyah", ayat: 118 },
    24: { nama: "An-Nur", arti: "Cahaya", type: "Madaniyah", ayat: 64 },
    25: { nama: "Al-Furqan", arti: "Pembeda", type: "Makkiyah", ayat: 77 },
    26: { nama: "Asy-Syu'ara'", arti: "Penyair", type: "Makkiyah", ayat: 227 },
    27: { nama: "An-Naml", arti: "Semut", type: "Makkiyah", ayat: 93 },
    28: { nama: "Al-Qasas", arti: "Kisah", type: "Makkiyah", ayat: 88 },
    29: { nama: "Al-'Ankabut", arti: "Laba-laba", type: "Makkiyah", ayat: 69 },
    30: { nama: "Ar-Rum", arti: "Bangsa Romawi", type: "Makkiyah", ayat: 60 },
    31: { nama: "Luqman", arti: "Nabi Luqman", type: "Makkiyah", ayat: 34 },
    32: { nama: "As-Sajdah", arti: "Sujud", type: "Makkiyah", ayat: 30 },
    33: { nama: "Al-Ahzab", arti: "Kabilah-kabilah", type: "Madaniyah", ayat: 73 },
    34: { nama: "Saba'", arti: "Saba'", type: "Makkiyah", ayat: 54 },
    35: { nama: "Fatir", arti: "Pencipta", type: "Makkiyah", ayat: 45 },
    36: { nama: "Ya-Sin", arti: "Ya-Sin", type: "Makkiyah", ayat: 83 },
    37: { nama: "As-Saffat", arti: "Barisan", type: "Makkiyah", ayat: 182 },
    38: { nama: "Sad", arti: "Sad", type: "Makkiyah", ayat: 88 },
    39: { nama: "Az-Zumar", arti: "Rombongan", type: "Makkiyah", ayat: 75 },
    40: { nama: "Ghafir", arti: "Pengampun", type: "Makkiyah", ayat: 85 },
    41: { nama: "Fussilat", arti: "Penjelasan", type: "Makkiyah", ayat: 54 },
    42: { nama: "Asy-Syura", arti: "Musyawarah", type: "Makkiyah", ayat: 53 },
    43: { nama: "Az-Zukhruf", arti: "Perhiasan", type: "Makkiyah", ayat: 89 },
    44: { nama: "Ad-Dukhan", arti: "Kabut", type: "Makkiyah", ayat: 59 },
    45: { nama: "Al-Jasiyah", arti: "Berlutut", type: "Makkiyah", ayat: 37 },
    46: { nama: "Al-Ahqaf", arti: "Bukit-bukit Pasir", type: "Makkiyah", ayat: 35 },
    47: { nama: "Muhammad", arti: "Nabi Muhammad", type: "Madaniyah", ayat: 38 },
    48: { nama: "Al-Fath", arti: "Kemenangan", type: "Madaniyah", ayat: 29 },
    49: { nama: "Al-Hujurat", arti: "Kamar-kamar", type: "Madaniyah", ayat: 18 },
    50: { nama: "Qaf", arti: "Qaf", type: "Makkiyah", ayat: 45 },
    51: { nama: "Adz-Dzariyat", arti: "Angin yang Menerbangkan", type: "Makkiyah", ayat: 60 },
    52: { nama: "At-Tur", arti: "Bukit", type: "Makkiyah", ayat: 49 },
    53: { nama: "An-Najm", arti: "Bintang", type: "Makkiyah", ayat: 62 },
    54: { nama: "Al-Qamar", arti: "Bulan", type: "Makkiyah", ayat: 55 },
    55: { nama: "Ar-Rahman", arti: "Maha Pengasih", type: "Madaniyah", ayat: 78 },
    56: { nama: "Al-Waqi'ah", arti: "Hari Kiamat", type: "Makkiyah", ayat: 96 },
    57: { nama: "Al-Hadid", arti: "Besi", type: "Madaniyah", ayat: 29 },
    58: { nama: "Al-Mujadilah", arti: "Wanita yang Mengajukan Gugatan", type: "Madaniyah", ayat: 22 },
    59: { nama: "Al-Hasyr", arti: "Pengusiran", type: "Madaniyah", ayat: 24 },
    60: { nama: "Al-Mumtahanah", arti: "Wanita yang Diuji", type: "Madaniyah", ayat: 13 },
    61: { nama: "As-Saff", arti: "Barisan", type: "Madaniyah", ayat: 14 },
    62: { nama: "Al-Jumu'ah", arti: "Hari Jum'at", type: "Madaniyah", ayat: 11 },
    63: { nama: "Al-Munafiqun", arti: "Orang-orang Munafik", type: "Madaniyah", ayat: 11 },
    64: { nama: "At-Taghabun", arti: "Hari Ditampakkan Segala Rahasia", type: "Madaniyah", ayat: 18 },
    65: { nama: "At-Talaq", arti: "Talak", type: "Madaniyah", ayat: 12 },
    66: { nama: "At-Tahrim", arti: "Mengharamkan", type: "Madaniyah", ayat: 12 },
    67: { nama: "Al-Mulk", arti: "Kerajaan", type: "Makkiyah", ayat: 30 },
    68: { nama: "Al-Qalam", arti: "Pena", type: "Makkiyah", ayat: 52 },
    69: { nama: "Al-Haqqah", arti: "Hari Kiamat", type: "Makkiyah", ayat: 52 },
    70: { nama: "Al-Ma'arij", arti: "Tempat-tempat Naik", type: "Makkiyah", ayat: 44 },
    71: { nama: "Nuh", arti: "Nabi Nuh", type: "Makkiyah", ayat: 28 },
    72: { nama: "Al-Jinn", arti: "Jin", type: "Makkiyah", ayat: 28 },
    73: { nama: "Al-Muzzammil", arti: "Orang yang Berselimut", type: "Makkiyah", ayat: 20 },
    74: { nama: "Al-Muddatstsir", arti: "Orang yang Berkabung", type: "Makkiyah", ayat: 56 },
    75: { nama: "Al-Qiyamah", arti: "Hari Kiamat", type: "Makkiyah", ayat: 40 },
    76: { nama: "Al-Insan", arti: "Manusia", type: "Madaniyah", ayat: 31 },
    77: { nama: "Al-Mursalat", arti: "Angin yang Dikirim", type: "Makkiyah", ayat: 50 },
    78: { nama: "An-Naba'", arti: "Berita Besar", type: "Makkiyah", ayat: 40 },
    79: { nama: "An-Nazi'at", arti: "Malaikat yang Mencabut", type: "Makkiyah", ayat: 46 },
    80: { nama: "'Abasa", arti: "Ia Bermuka Masam", type: "Makkiyah", ayat: 42 },
    81: { nama: "At-Takwir", arti: "Menggulung", type: "Makkiyah", ayat: 29 },
    82: { nama: "Al-Infitar", arti: "Terbelah", type: "Makkiyah", ayat: 19 },
    83: { nama: "Al-Mutaffifin", arti: "Orang-orang yang Curang", type: "Makkiyah", ayat: 36 },
    84: { nama: "Al-Insyiqaq", arti: "Terbelah", type: "Makkiyah", ayat: 25 },
    85: { nama: "Al-Buruj", arti: "Gugusan Bintang", type: "Makkiyah", ayat: 22 },
    86: { nama: "At-Tariq", arti: "Bintang yang Tampak di Malam Hari", type: "Makkiyah", ayat: 17 },
    87: { nama: "Al-A'la", arti: "Maha Tinggi", type: "Makkiyah", ayat: 19 },
    88: { nama: "Al-Ghashiyah", arti: "Hari Pembalasan", type: "Makkiyah", ayat: 26 },
    89: { nama: "Al-Fajr", arti: "Fajar", type: "Makkiyah", ayat: 30 },
    90: { nama: "Al-Balad", arti: "Negeri", type: "Makkiyah", ayat: 20 },
    91: { nama: "Asy-Syams", arti: "Matahari", type: "Makkiyah", ayat: 15 },
    92: { nama: "Al-Lail", arti: "Malam", type: "Makkiyah", ayat: 21 },
    93: { nama: "Adh-Dhuha", arti: "Waktu Dhuha", type: "Makkiyah", ayat: 11 },
    94: { nama: "Alam Nashrah", arti: "Pembukaan", type: "Makkiyah", ayat: 8 },
    95: { nama: "At-Tin", arti: "Buah Tin", type: "Makkiyah", ayat: 8 },
    96: { nama: "Al-'Alaq", arti: "Segumpal Darah", type: "Makkiyah", ayat: 19 },
    97: { nama: "Al-Qadr", arti: "Kemuliaan", type: "Makkiyah", ayat: 5 },
    98: { nama: "Al-Bayyinah", arti: "Bukti yang Jelas", type: "Madaniyah", ayat: 8 },
    99: { nama: "Az-Zalzalah", arti: "Kegoncangan", type: "Madaniyah", ayat: 8 },
    100: { nama: "Al-'Adiyat", arti: "Kuda yang Berlari Kencang", type: "Makkiyah", ayat: 11 },
    101: { nama: "Al-Qari'ah", arti: "Hari Kiamat", type: "Makkiyah", ayat: 11 },
    102: { nama: "At-Takatsur", arti: "Bermegah-megahan", type: "Makkiyah", ayat: 8 },
    103: { nama: "Al-'Asr", arti: "Masa", type: "Makkiyah", ayat: 3 },
    104: { nama: "Al-Humazah", arti: "Pengumpat", type: "Makkiyah", ayat: 9 },
    105: { nama: "Al-Fil", arti: "Gajah", type: "Makkiyah", ayat: 5 },
    106: { nama: "Quraisy", arti: "Suku Quraisy", type: "Makkiyah", ayat: 4 },
    107: { nama: "Al-Ma'un", arti: "Barang yang Berguna", type: "Makkiyah", ayat: 7 },
    108: { nama: "Al-Kautsar", arti: "Nikmat yang Berlimpah", type: "Makkiyah", ayat: 3 },
    109: { nama: "Al-Kafirun", arti: "Orang-orang Kafir", type: "Makkiyah", ayat: 6 },
    110: { nama: "An-Nashr", arti: "Pertolongan", type: "Madaniyah", ayat: 3 },
    111: { nama: "Al-Lahab", arti: "Gejolak Api", type: "Makkiyah", ayat: 5 },
    112: { nama: "Al-Ikhlas", arti: "Ikhlas", type: "Makkiyah", ayat: 4 },
    113: { nama: "Al-Falaq", arti: "Waktu Subuh", type: "Makkiyah", ayat: 5 },
    114: { nama: "An-Nas", arti: "Manusia", type: "Makkiyah", ayat: 6 },
};
